### ISSUE TITLE
https://virginradio.ro/live/

### ISSUE THREAD

**Issue by seba2282** [tcptomato/ROad-Block#51]
Pagină URL (necesar) : 
https://virginradio.ro/live/

Screenshot (optional)  : 
![Screenshot_2019-04-05-21-40-58](https://user-images.githubusercontent.com/16944478/55652546-0805b180-57ec-11e9-9d18-b7e81e9f41e8.png)

Banner ads under player.

**Comment by tcptomato** [comment]
Mersi. Am adaugat si noua reclama de la europafm in lista, intr-un mod care ar trebui sa functioneze si in viitor. Have a look daca merge cum trebuie.

**Comment by seba2282** [comment]
Actually on EuropaFM and Virgin Radio I see banner ads. I know, I must wait few hours for update filters. And after I will tell works or not.

**Comment by tcptomato** [comment]
You can force an update in the uBlock  options / filter lists

**Comment by seba2282** [comment]
In Nano Adblocker show me updated list and as newest from 1.04.2019 Road-Block List. So need time.

**Comment by seba2282** [comment]
![Screenshot_2019-04-09-17-26-01](https://user-images.githubusercontent.com/16944478/55813260-c8411180-5aec-11e9-9e00-aaf535bbe14d.png)
That is actually on virginradio.ro/live 
All filters updated. Now any problem with europafm.ro/live , because here all works now fine.

**Comment by tcptomato** [comment]
I ugly fixed it for the time being.

On both sites I tried killing the div the ad is displayed, so that I don't have to update the list for each new ad they use ( I couldn't make a general filter, because it also kills non-ad parts of the site). The current solution will probably break on mobile when they update to a new ad, but I'll keep looking for a solution. Thanks for reporting.

**Comment by seba2282** [comment]
Welcome. And wait for fix.

**Comment by seba2282** [comment]
@tcptomato, thank you for fixed. Europa Fm and Virgin Radio haven't banner ads. 🙂
